# Generated by Django 4.1.4 on 2023-02-11 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_rename_files_memories_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
