# Generated by Django 4.1.4 on 2023-02-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0011_alter_memories_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
