# Generated by Django 4.1.4 on 2023-02-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0012_events_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
