# Generated by Django 4.1.4 on 2023-02-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0013_debts_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
